version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nestjs-production
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nestjs-app
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: nestjs-network
